config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    get '/admin', to: redirect('/admin/dashboard')
    
    namespace :admin do
      get 'dashboard', to: 'pages#dashboard'
      resources :clients
      resources :tickets do
        resources :comments, only: [:new, :create, :edit, :update]
      end
      resources :users
      resources :comments, only: [:destroy]
    end
  
    resources :clients, only: [:show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
#Defaults
    enum status: [ :active, :inactive, :potential ]
    enum service_type: [ :contract, :billable, :pending]
    enum payment_method: [ :credit_card, :cash, :check, :undefined]
    paginates_per 10
#Relationships
    has_many :tickets
    has_many :users
    has_one :primary_contact, -> { where(is_primary: true) }, class_name: "User"
    
#Validations
    validates :name, presence: true, length: { in: 3..60 }
    validates :status, presence: true
    validates :service_type, presence: true
    validates :payment_method, presence: true
    validates :street, presence: true, length: { in: 6.. 40 }
    validates :city, presence: true, length: { in: 3..25 }
    validates :state, presence: true, length: { is: 2 }
    validates :zipcode, presence: true, numericality: true


#Methods
    def active_ticket_count
        tickets.active.count
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    default_scope { order(created_at: :desc) }
    
    belongs_to :commentable, polymorphic: true
    belongs_to :user

    validates :body, presence: true, length:  :within [15..500] 

    after_save :touch_commentable
    
    def touch_commentable
        self.commentable.touch(:last_response)
    end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
#defaults
    enum status: [ :pending_review, :in_progress, :on_hold, :resolved ]
    enum severity: [ :P1, :P2, :P3, :P4]
    paginates_per 10  
#Relationships  
    belongs_to :client
    belongs_to :user
    has_many :comments, as: :commentable
  
#validations
    validates :ticket_number, presence: true, allow_nil: true
    validates :request_detail, presence: true
    validates :request_summary, presence: true
    validates :severity, presence: true
    validates :status, presence: true
    
#Scopes
    scope :active, -> { where(status: "active") }
    
#Methods
    def assign_ticket_number
        self.update_column(:ticket_number, "Ticket-#{self.id}")
    end
    
    def days_pending
        return "1"
    end
#Callbacks
    after_save :assign_ticket_number
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :client
  has_many :tickets
    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
    layout 'admin' 
    def index
        @q = Client.ransack(params[:q])
        @clients = @q.result.includes(:primary_contact).page(params[:page])
        @tickets = Ticket.active.limit(3).load
        
        respond_to do |f|
            f.js { render 'index.js.erb' }
            f.html
        end
    end
    
    def show
        @client = Client.includes([tickets: :user], :primary_contact).find(params[:id])
    end
    
    def new
        @client = Client.new
    end
    
    def create
        @client = Client.new(client_params)
        
        if @client.save 
            redirect_to @client
        else
            render :new
        end
    end 
    
    def edit
        @client = Client.find(params[:id])
    end
    
    def update
        @client = Client.find(params[:id])
        if @client.udpate(client_params)
            redirect_to @client
        else
            render :edit
        end
    end
    
    def destroy
        @client = Client.find(params[:id])
        @client.delete
        
        redirect_to admin_clients_path
    end
    
    private
        def client_params
            params.require(:client).permit(:name, :status, :service_type, :payment_method, :onboard_date, :offboard_date, :recent_request_date, :account_current, :street, :city, :state, :zipcode)
        end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def create
    @content = get_commentable
    @comment = @content.comments.create(comment_params)
    
    respond_to do |format|    
        if(@comment.save)
            format.html { redirect_to [:admin, @content] }
            format.json
        else
            format.html { render :new }
            format.js { @messages }
        end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def comment_params
        params.require(:comment).permit(:body, :user_id, :commentable)
    end
    def get_commentable
        params.each do |name, value|
            if name =~ /(.+)_id$/
                return $1.classify.constantize.find(value) 
            end
        end
        nil 
    end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
    layout 'admin'
    def dashboard
        @tickets = Ticket.active
    end

end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < ApplicationController
    layout 'admin'
    before_action :set_ticket, only: [:show]
    def index
#        @tickets = Ticket.includes(:client).all
        @q = Ticket.ransack(params[:q])
        @tickets = @q.result.includes(:client, :user, :comments).page(params[:page])
        
        respond_to do |f|
            f.js { render 'index.js.erb' }
            f.html
        end
    end
    def show; end
  
    def new
        @ticket = Ticket.new
    end
    
    def create
        @ticket = Ticket.create(ticket_params)
        if @ticket.save
            redirect_to admin_ticket_path(@ticket)
        else
            render :new
        end
    end
    
    def edit; end
    
    def update 
        if @ticket.update(ticket_params)
            redirect_to admin_ticket_path(@ticket)
        else
            render :edit
        end
    end
    
    def destroy
        @ticket.destroy
        redirect_to admin_client_path(@ticket.client)
    end
    
    private
        def ticket_params
            params.require(:ticket).permit(:ticket_number, :request_summary, :request_detail, :outcome_summary, :outcome_detail, :due, :resolved, :last_response, :severity, :status, :client_id, :user_id)
        end
        
        def set_ticket
            @ticket = Ticket.find(params[:id])
        end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    layout 'admin'
    before_action :set_user, only: [:show, :edit, :update, :new]
    
    def index
        @users = User.all
    end
    
    def show
    end
    
    def new
    end
    
    def create
    end
    
    def edit
    end
    
    def update
    end
    
    def destroy
    end

    private
        def user_params
            Params.require(:user).permit(:first_name, :last_name, :email, :primary_phone, :secondary_phone, :client)
        end
        
        def set_user
            @user = User.find(params[:id])
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    def show
        @client = Client.find(params[:id])
    end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/tickets_helper.rb
module Admin::TicketsHelper

    def status_styler(status)
        case status
        when "pending_review"
            ("<span class='tag is-white is-pulled-right'>Pending Review</span>").html_safe
        when "in_progress"
            ("<span class='tag is-primary is-pulled-right'>In Progress</span>").html_safe
        when "on_hold"
            ("<span class='tag is-danger is-pulled-right'>On hold</span>").html_safe
        when "resolved"
            ("<sspan class='tag is-success is-pulled-right'>Resolved</span>").html_safe
        else
            ("<span class='tag is-light is-pulled-right'>#{status}</span>").html_safe
        end
    end
end

app/helpers/admin/userscontroller_helper.rb
module Admin::UserscontrollerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/admin/clients/_client.html.erb
<tr data-url="<%= admin_client_path(client) %>">
    <td><%= client.id %></td>
    <td><%= client.name %></td>
    <td><%= client.primary_contact.full_name %></td>
    <td><%= client.status %></td>
    <td>
        <%= link_to(edit_admin_client_path(client)) do %><i class="far fa-pencil" style='margin: 0 5px;'></i><% end %>
        <i class="far fa-envelope" style='margin: 0 5px;'></i>
        <i class="far fa-usd-circle" style='margin: 0 5px;'></i>
</div>
    </td>
    
</tr>

app/views/admin/clients/_primary_contact.html.erb
<div class='box'>
                    <h3 class='has-text-weight-semibold'><%= pc.full_name %></h3>
                    <h4>Lead Banana Maker<h4>
                    <br />
                    <span class='has-text-weight-semibold'>Contact Details</span>
                    <ul>
                        <li><i class="far fa-phone"></i> <%= pc.primary_phone %></li>
                        <li><i class="far fa-at"></i> <%= pc.email %></li>
                    </ul>
                </div>

app/views/admin/clients/_ticket.html.erb
<tr data-url="<%= admin_ticket_path(ticket) %>">
    <td><%= ticket.ticket_number %></td>
    <td><%= ticket.user.full_name %></td>
    <td><%= ticket.request_summary %></td>
    <td><i class="far fa-comment-alt" style='margin-right: 10px;'></i> <i class="far fa-check-square"></i></td>
</tr>

app/views/admin/clients/index.html.erb
<section class="section">
    <div class="container">
        <div class='columns'>
            <div class='column is-three-quarters'>
                <h1 class="title is-inline-block" style='margin-right: 15px;'>Clients</h1>
                <span class='is-inline-block'>
                <%= search_form_for([:admin, @q], html: {style: 'width: 250px'}) do |f| %>
                
                <div class="field">
  <p class="control has-icons-left" style='250px'>
    <%= f.search_field :name_cont, class: 'client_search input is-rounded' %>
    <span class="icon is-small is-left">
      <i class="far fa-search"></i>
    </span>
  </p>
</div>

  <%= f.submit "search", class:"button is-info is-hidden" %>
<% end %></span>
                
<!--                  <i class="far fa-filter fa-lg" style='margin-bottom: 5px; margin-left: 5px;'></i>
              <i class="far fa-sort fa-lg" style='margin-bottom: 5px; margin-left: 5px;'></i> -->
                <span class='is-pulled-right'>
                    <%= link_to(new_admin_client_path, class: "button is-primary") do %>
                            <i class="far fa-plus-circle" style='margin-right: 5px;'></i> Create Client
                    <% end %> 
                </span>
                <table class='table is-fullwidth is-hoverable clickable_row'>
                    <thead style="background-color: #e9eff5;">
                        <tr>
                            <th><%= sort_link(@q, :id) %></th>
                            <th><%= sort_link(@q, :name, 'Client Name') %></th>
                            <th><%= sort_link(@q, :primary_contact) %></th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody class='page_clients'>
                        <%= render @clients %>  
                    </tbody>
                </table>
                <div id='paginator'>
                    <%= paginate @clients, remote: true %>
                </div>
            </div>
            <div class='column'>
                <section>
                    <h2 class='title' style='display: inline-block; margin-right: 15px;'>Recent Activity</h2>
                    <div class='box' style='min-height: 150px'></div>
                </section>
                <br />
                <section>
                    <h2 class="title is-inline-block" style='margin-right: 15px;'>Tickets</h2>
                    <span class='is-pulled-right' style='margin-top: 10px;'><%= link_to('View All >>', admin_tickets_path) %></span>
                    <div class='box' style='min-height: 150px'>
                        <% @tickets.each do |t| %>
                            <%= link_to(admin_ticket_path(t)) do %>
                                <%= t.ticket_number + " - " + t.client.name + " - " + t.days_pending + " day" %>
                            <% end %>
                            <br>
                        <% end %>
                    </div>              
                </section>
            </div>
        </div>
    </div>
</section>

app/views/admin/clients/index.js.erb
$(".page_clients").html("<%= escape_javascript render(@clients) %>"); 
$("#paginator").html("<%= escape_javascript(paginate(@clients, remote: true)) %>");

app/views/admin/clients/new.html.erb
<div class='section'>
    <div class='container'>
        <div class='columns'>
            <div class='column is-half is-offset-one-quarter'>
                <h1 class='title'>New Client</h1>
                <%= form_for [:admin, @client] do |f| %>
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'input' %>
                <% end %>            
            </div>
        </div>
    </div>
    

app/views/admin/clients/show.html.erb
<div class='container'>
    <%= link_to("<< Clients", admin_clients_path) %>
</div>
<section class='section'>
    <div class='container'>
        <div class='columns'>
            <div class='column is-three-quarters'>
                <h1 class='title is-inline-block' style='margin-bottom: 5px;'><%= @client.name %></h1>
                <span class='is-pulled-right'>
                    <%= link_to('#') do %>
                        <i class='far fa-envelope fa-lg' style='margin-top: 10px; margin-right: 10px'></i>
                    <% end %>
                    <%= link_to(edit_admin_client_path(@client)) do %>
                        <i class='far fa-cog fa-lg' style='margin-top: 10px margin-right: 10px'></i>
                    <% end %>
                </span>
                <hr style='margin: 10px 0'/>
                <div>
                    <address>
                        <%= @client.street %><br />
                        <%= @client.city %> <%= @client.state %>, <%= @client.zipcode %>
                    </address>
                </div>
            </div>
            <div class='column'>
                <h1 class='title is-inline-block'>Primary Contact</h1>
                <span class='is-pulled-right'>
                    <%= link_to('#') do %>
                        <i class="far fa-user-cog fa-lg" style='margin-top: 10px;'></i>
                    <% end %>
                </span>
                <%= render 'primary_contact', pc: @client.primary_contact %>
        </div>
    </div>
</section>
<section class='section'>
    <div class='container'>
        <div class='columns'>
            <div class='column is-three-quarters'>
                <h1 class='title is-inline-block'>Projects</h1>
                <span class='is-pulled-right'>
                    <%= link_to('#', class: 'button is-primary') do %>
                        <i class="far fa-plus-circle" style='margin-right: 10px;'></i>Create Project
                    <% end %>    
                </span>
                <div class='box'>
                </div>
            </div>
        </div>
    </div>
</section>
<section class='section'>
    <div class='container'>
        <div class='columns'>
            <div class='column is-three-quarters'>
                <h1 class='title is-inline-block'>Tickets</h1>
                <span class='is-pulled-right'>
                    <%= link_to(new_admin_ticket_path, class: 'button is-primary') do %>
                        <i class="far fa-plus-circle" style='margin-right: 10px;'></i>Create Ticket
                    <% end %>    
                </span>
                <table class='table is-hoverable is-fullwidth clickable_row'>
                    <thead>
                        <tr>
                            <th>Ticket Number</th>
                            <th>Logged By</th>
                            <th>Summary</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <%= render partial: 'ticket', collection: @client.tickets %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

app/views/admin/comments/_comment.html.erb
 <div class='columns'>
    <div class='column'>
        <div class='box'>
            <%= comment.body %>
            <br />
            <br />
            <nav class="level">
              <div class="level-left">
                <div class='level-item'>
                  Commentor: <%= comment.user.full_name %>
                </div>
              </div>
        
              <div class="level-right">
                <div class='level-item'>
                    <span class='is-italic'>
                        <%= comment.created_at.strftime("created %m/%d/%Y %T %p") %>
                    </span>
                </div>
              </div>
            </nav>
        </div>
    </div>
</div>

app/views/admin/comments/_new.html.erb
<%= form_for([:admin, @ticket, Comment.new], remote: true) do |f| %>
    <div id='form_errors'>
        
    </div>
    
    <%= f.label :body, "New Comment", class: 'label' %>
    <%= f.text_area :body, class: 'textarea' %>
    <%= f.hidden_field(:user_id, value: 1) %>
    <br />
    <div class=''>
        <%= button_tag(type: 'submit', class: 'button is-success is-medium is-fullwidth', "data-disable-with"=> "Just a moment...") do %><i class="far fa-paper-plane"></i><% end %>
    </div>
    </br>
<% end %>

app/views/admin/comments/create.js.erb
<% if @comment.errors.any? %>
  $("#form_errors").html("<%= escape_javascript(render 'admin/shared/remote_errors', errors: @comment.errors.full_messages) %>");
<% else %>
    $("#comments_container").prepend("<%= escape_javascript(render 'admin/comments/comment', comment: @comment ) %>");
    $("#last_response_block").html("<%= @content.last_response.strftime('Last Updated: %m/%d/%Y %T %p') %>");
    $("#comment_body").val("");
<% end %>

app/views/admin/comments/destroy.js.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

app/views/admin/comments/edit.html.erb
<h1>Admin::Comments#edit</h1>
<p>Find me in app/views/admin/comments/edit.html.erb</p>

app/views/admin/comments/update.js.erb
<h1>Admin::Comments#update</h1>
<p>Find me in app/views/admin/comments/update.html.erb</p>

app/views/admin/pages/dashboard.html.erb
<section class="section">
    <div class="container">
        <div class='columns'>
            <div class='column is-three-quarters'>
                <h1 class="title" style='display: inline-block; margin-right: 15px;'>Dashboard</h1>
                <nav class="level">
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Open Tickets</p>
      <p class="title"><%= @tickets.count %></p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Open POs</p>
      <p class="title">$100,000.00</p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Avg Ticket Age</p>
      <p class="title">65 days</p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Past Due Accounts</p>
      <p class="title">1</p>
    </div>
  </div>
</nav>

            </div>
            <div class='column'>
                <section>
                    <h2 class='title' style='display: inline-block; margin-right: 15px;'>Quick Actions</h2>
                    <div class='box' style='height: 135px'>
                        <ul>
                            <li><%= link_to('Clients', admin_clients_path) %></li>
                            <li><%= link_to('Tickets', admin_tickets_path) %></li>
                            <li><%= link_to('Billing', '#') %></li>
                            <li><%= link_to('TBD', '#') %></li>
                        </ul>
                    </div>
                </section>
            </div>
        </div>
    </div>
</section>
<section class='section'>
    <div class='container'>
        <div class='columns'>
            <div class='column'>
                <h1 class="title" style='display: inline-block; margin-right: 15px;'>Recent Activity</h1>
                <table class='table is-fullwidth'>
                    <thead style="background-color: #e9eff5;">
                        <tr>
                            <th>ID</th>
                            <th>Action</th>
                            <th>Description</th>
                            <th>Date</th>
                            <th>Executed By</th>
                        </tr>
                    </thead>
                    <tbody>
                
                    </tbody>
                </table>
            </div>
            </div>
        </div>
    </div>
</section>

app/views/admin/pages/tickets.html.erb
<% @tickets.each do |t| %>
    <li><%= t.ticket_number %> - <%= t.client.name %></li>
<% end %>

app/views/admin/shared/_nav.html.erb
<header>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
            Bifrost
        </a>
    
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
    
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to("Dashboard", admin_dashboard_path, class: "navbar-item") %>
          <%= link_to("Clients", admin_clients_path, class: "navbar-item") %>
          <%= link_to("Tickets", admin_tickets_path, class: "navbar-item") %>
        </div>
    
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light">
                Log in
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>
</header>

app/views/admin/shared/_remote_errors.html.erb
<article class="message is-danger">
  <div class="message-header">
    <p>Error</p>
    <button class="delete" aria-label="delete"></button>
  </div>
  <div class="message-body">
    <% errors.each do |e| %>
        <li><%= e %></li>
    <% end %>
  </div>
</article>

app/views/admin/tickets/_ticket.html.erb
<tr>
    <td><%= ticket.ticket_number %></td>
    <td><%= ticket.user.full_name %></td>
    <td><%= ticket.client.name %></td>
    <td><%= ticket.severity %></td>
</tr>

app/views/admin/tickets/index.html.erb
<section class='section'>
    <div class='container'>
        <div class='columns'>
            <div class='column'>
                <table class='table'>
                    <thead>
                        <tr>
                            <th><%= sort_link(@q, :ticket_number, 'Ticket Number') %></th>
                            <th><%= sort_link(@q, :user_first_name, 'Full Name') %></th>
                            <th><%= sort_link(@q, :client_name, 'Client') %></th>
                            <th><%= sort_link(@q, :severity) %></th>
                        </tr>
                    </thead>
                    <tbody class='page_tickets'>
                        <%= render @tickets %>
                    </tbody>
                </table>  
                <div id='paginator'>
                    <%= paginate @tickets, remote: true %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/admin/tickets/index.js.erb
$(".page_tickets").html("<%= escape_javascript render(@tickets) %>"); 
$("#paginator").html("<%= escape_javascript(paginate(@tickets, remote: true)) %>");

app/views/admin/tickets/new.html.erb
<% if @ticket.errors.any? %>
    <section class='section'>
        <div class='container'>
            <div class='columns'>
                <div class='column is-half is-offset-one-quarter'>
                    <ul>
                    <% @ticket.errors.full_messages.each do |e| %>
                        <li><%= e %></i>
                    <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </section>
<% end %>
<section class='section'>
    <div class='container'>
        <div class='columns'>
            <div class='column is-half is-offset-one-quarter'>
                <h1 class='title'>New Ticket</h1>
                <%= form_for [:admin, @ticket] do |f| %>
                    <%= f.label :request_summary, class: 'label' %>
                    <%= f.text_field :request_summary, class: 'input' %>
                    
                    <%= f.label :request_detail, class: 'label' %>
                    <%= f.text_area :request_detail, rows: 10,  class: 'textarea' %>
                    <%= f.label :severity, class: 'label' %>
                    <div class='select'>
                        <%= f.select :severity, Ticket.severities.keys.map { |w| [w.humanize, w] } %>
                    </div>
                    
                    <%= f.hidden_field :client_id, value: 1 %>
                    <%= f.hidden_field :user_id, value: 1 %>
                    <%= f.hidden_field :status, value: "active" %>
                    
                    <%= f.submit 'Submit Ticket', class: 'button is-success' %>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/admin/tickets/show.html.erb
<section class='section'>
    <div class='container'>
        <div class='columns'>
            <div class='column is-half is-offset-one-quarter'>
                

                <div class='box'>
                    <h4 class='title is-4'>Request Details</h4>
                    <p><%= @ticket.request_detail %>
                    </p>
                </div>
                <h4 class='title is-4'>Request Updates</h4>
                <hr>
                    <div id='comment_form'>
                        <%= render 'admin/comments/new' unless @ticket.status == 'resolved' %>
                    </div>
                <div id='comments_container'>
                    <%= render partial: 'admin/comments/comment', collection: @ticket.comments %>
                </div>
            </div>
            <div class='column'>
                <div class='box' style='position: sticky; top: 75px;'>
                    <h1 class='title is-inline-block'><%= @ticket.ticket_number %></h1>
                    <%= status_styler(@ticket.status) %>
                    <div id='ticket_details'>
                        <span class='has-text-weight-bold'>Client:</span> <%= link_to(@ticket.client.name, admin_client_path(@ticket.client)) %><br />
                        <span class='has-text-weight-bold'>Requestor:</span> <%= link_to(@ticket.user.full_name, admin_user_path(@ticket.user)) %>
                    </div>
                    <span id='last_response_block' class='is-italic'>
                         <%= @ticket.last_response.strftime('Last Updated: %m/%d/%Y %T %p') %>
                    </span>
                    <br /><br />
                    <%= link_to("Mark Complete", "", class: 'button is-primary is-fullwidth') %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/admin/users/create.html.erb
<h1>Admin::Userscontroller#create</h1>
<p>Find me in app/views/admin/userscontroller/create.html.erb</p>

app/views/admin/users/destroy.html.erb
<h1>Admin::Userscontroller#destroy</h1>
<p>Find me in app/views/admin/userscontroller/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<h1>Admin::Userscontroller#edit</h1>
<p>Find me in app/views/admin/userscontroller/edit.html.erb</p>

app/views/admin/users/index.html.erb
<h1>Admin::Userscontroller#index</h1>
<p>Find me in app/views/admin/userscontroller/index.html.erb</p>

app/views/admin/users/new.html.erb
<h1>Admin::Userscontroller#new</h1>
<p>Find me in app/views/admin/userscontroller/new.html.erb</p>

app/views/admin/users/show.html.erb
<h1>Admin::Userscontroller#show</h1>
<p>Find me in app/views/admin/userscontroller/show.html.erb</p>

app/views/admin/users/update.html.erb
<h1>Admin::Userscontroller#update</h1>
<p>Find me in app/views/admin/userscontroller/update.html.erb</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bifrost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "admin/shared/nav" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_breadcrumb.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href='#'>Admin</a></li>
    <li><%= link_to("Dashboard", admin_dashboard_path) %></li>
    <li class="is-active"><%= link_to('Clients', admin_clients_path) %></li>
  </ul>
</nav>

app/views/shared/_nav.html.erb
<header>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
            Bifrost
        </a>
    
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
    
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to("Dashboard", admin_dashboard_path, class: "navbar-item") %>
    
          <%= link_to("Clients", admin_clients_path, class: "navbar-item") %>
        </div>
    
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light">
                Log in
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>
</header>